= API Guide
api;
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:
:operation-curl-request-title: Example request
:operation-http-response-title: Example response

[[resources]]
= 리소스

[[resources-index]]
== 인덱스

auth API는 인증 서비스를 제공한다.

[[get-access_token-password-grantType]]
=== 엑세스 토근 발급 - Password 방식

`POST` 요청을 사용하여 엑세스 토큰을 발급받을 수 있다.

operation::get-access_token-password-grantType[snippets='curl-request,http-request,request-headers,request-parameters,http-response,response-headers,response-fields']

[[get-access_token-client_credentials-grantType]]
=== 엑세스 토근 발급 - Client Credentials 방식

`POST` 요청을 사용하여 엑세스 토큰을 발급받을 수 있다.

operation::get-access_token-client_credentials-grantType[snippets='curl-request,http-request,request-headers,request-parameters,http-response,response-headers,response-fields']

[[get-access_token-refresh_token-grantType]]
=== 엑세스 토근 발급 - Refresh Token 방식

`POST` 요청을 사용하여 재발급 토큰을 전송하여 인증없이 엑세스 토큰을 재발급받을 수 있다.

operation::get-access_token-refresh_token-grantType[snippets='curl-request,http-request,request-headers,request-parameters,http-response,response-headers,response-fields']

[[check-access_token]]
=== 엑세스 토큰 확인

`POST` 요청을 사용하여 엑세스 토큰을 전송하여 토큰의 유효성 여부를 확인할 수 있다.

operation::check-access_token[snippets='curl-request,http-request,request-parameters,http-response,response-headers,response-fields']

[[revoke-access_token]]
=== 엑세스 토큰 만료

`POST` 요청을 사용하여 엑세스 토큰을 전송하여 토근을 만료시킬 수 있다.

operation::revoke-access_token[snippets='curl-request,http-request,request-headers,http-response,response-headers,response-fields']

[[get-me]]
=== 엑세스 토큰 발급 유저 정보 조회

`GET` 요청을 사용하여 엑세스 토큰을 발급받은 유저의 정보를 조회할 수 있다.

operation::get-me[snippets='curl-request,http-request,request-headers,http-response,response-headers,response-fields']